import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import DashboardLayout from '../layouts/DashboardLayout';
import PageHeader from '../components/PageHeader';
import { createMeeting, findSlots, getExecutives } from '../services/meetingService';

function CreateMeeting() {
  const navigate = useNavigate(); const [executives, setExecutives] = useState([]); const [slots, setSlots] = useState([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', purpose: '', venue: '', meeting_date: '', duration: 60, participant_ids: [], start_time: '', end_time: '' });
  useEffect(() => { getExecutives().then((data) => setExecutives(data.executives)).catch(() => setError('Could not load executives.')); }, []);
  function update(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  function toggleExecutive(id) { setForm({ ...form, participant_ids: form.participant_ids.includes(id) ? form.participant_ids.filter((item) => item !== id) : [...form.participant_ids, id] }); }
  async function searchSlots() { try { setError(''); const data = await findSlots({ executiveIds: form.participant_ids, date: form.meeting_date, duration: Number(form.duration) }); setSlots(data.availableSlots); if (!data.availableSlots.length) setError('No common free slot is available. Try another date, duration, or participants.'); } catch (err) { setError(err.response?.data?.message || 'Could not find slots.'); } }
  function selectSlot(slot) { setForm({ ...form, start_time: slot.startTime, end_time: slot.endTime }); }
  async function submit(event) { event.preventDefault(); try { await createMeeting(form); navigate('/meetings'); } catch (err) { setError(err.response?.data?.message || 'Could not schedule meeting.'); } }
  return <DashboardLayout><PageHeader title="Schedule Meeting" description="Choose executives, find a free time, then schedule the meeting." /><form className="space-y-4 rounded-lg bg-white p-6 shadow-sm" onSubmit={submit}><input className="w-full rounded border p-2" placeholder="Meeting title" name="title" value={form.title} onChange={update} /><textarea className="w-full rounded border p-2" placeholder="Purpose" name="purpose" value={form.purpose} onChange={update} /><div className="grid gap-3 sm:grid-cols-2"><input className="rounded border p-2" type="date" name="meeting_date" value={form.meeting_date} onChange={update} /><input className="rounded border p-2" type="number" min="30" step="30" name="duration" value={form.duration} onChange={update} placeholder="Duration (minutes)" /></div><div><p className="mb-2 font-medium">Invite executives</p>{executives.map((executive) => <label className="mr-4 inline-flex gap-2" key={executive.id}><input type="checkbox" checked={form.participant_ids.includes(executive.id)} onChange={() => toggleExecutive(executive.id)} />{executive.full_name}</label>)}</div><button type="button" className="rounded bg-slate-800 px-4 py-2 text-white" onClick={searchSlots}>Find Available Slots</button>{slots.length > 0 && <div className="rounded bg-blue-50 p-4"><p className="font-medium">Available slots</p>{slots.map((slot) => <button type="button" key={slot.startTime} className="mr-2 mt-2 rounded border bg-white px-3 py-2" onClick={() => selectSlot(slot)}>{slot.startTime} – {slot.endTime}</button>)}</div>}<div className="grid gap-3 sm:grid-cols-3"><input className="rounded border p-2" placeholder="Venue" name="venue" value={form.venue} onChange={update} /><input className="rounded border p-2" type="time" name="start_time" value={form.start_time} onChange={update} /><input className="rounded border p-2" type="time" name="end_time" value={form.end_time} onChange={update} /></div>{error && <p className="text-red-600">{error}</p>}<button className="rounded bg-blue-700 px-4 py-2 text-white">Schedule Meeting</button></form></DashboardLayout>;
}
export default CreateMeeting;
