import { useEffect, useState } from 'react';
import DashboardLayout from '../layouts/DashboardLayout';
import PageHeader from '../components/PageHeader';
import DashboardCard from '../components/DashboardCard';
import { getAnalytics, getReportDashboard } from '../services/reportService';

function Reports() {
  const [dashboard, setDashboard] = useState(null); const [analytics, setAnalytics] = useState(null); const [period, setPeriod] = useState('month'); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [error, setError] = useState('');
  async function load() { try { setError(''); const params = period === 'custom' ? { startDate, endDate } : { period }; const [summary, details] = await Promise.all([getReportDashboard(), getAnalytics(params)]); setDashboard(summary); setAnalytics(details); } catch (err) { setError(err.response?.data?.message || 'Could not load reports.'); } }
  useEffect(() => { if (period !== 'custom') load(); }, [period]);
  if (!dashboard || !analytics) return <DashboardLayout><PageHeader title="Reports & Analytics" description="Review schedules and work activity." />{error ? <p className="text-red-600">{error}</p> : <p>Loading reports...</p>}</DashboardLayout>;
  const cards = [['Appointments', dashboard.totalAppointments], ['Meetings', dashboard.totalMeetings], ['Projects', dashboard.totalProjects], ['Leave Requests', dashboard.totalLeaveRequests], ['Tasks', dashboard.totalPersonalTasks], ['Completed Tasks', dashboard.completedTasks], ['Pending Tasks', dashboard.pendingTasks], ['Upcoming Meetings', dashboard.upcomingMeetings], ['Upcoming Appointments', dashboard.upcomingAppointments]];
  const trend = analytics.charts.appointments; const maximum = Math.max(...trend.map((item) => Number(item.total)), 1);
  return <DashboardLayout><div className="flex flex-wrap items-start justify-between gap-3"><PageHeader title="Reports & Analytics" description="Schedule, task, leave, and project activity." /><div className="flex flex-wrap gap-2"><select className="rounded border bg-white p-2" value={period} onChange={(event) => setPeriod(event.target.value)}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="year">This year</option><option value="custom">Custom range</option></select>{period === 'custom' && <><input className="rounded border p-2" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /><input className="rounded border p-2" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /><button className="rounded bg-blue-700 px-3 text-white" onClick={load}>Apply</button></>}</div></div>{error && <p className="mb-3 text-red-600">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([title, value]) => <DashboardCard key={title} title={title} value={value} />)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-lg bg-white p-5 shadow-sm"><h2 className="font-semibold">Appointments over time</h2>{trend.length ? <div className="mt-4 space-y-3">{trend.map((item) => <div key={item.date}><div className="flex justify-between text-sm"><span>{String(item.date).slice(0, 10)}</span><span>{item.total}</span></div><div className="h-3 rounded bg-slate-100"><div className="h-3 rounded bg-blue-600" style={{ width: `${(Number(item.total) / maximum) * 100}%` }} /></div></div>)}</div> : <p className="mt-3 text-slate-500">No appointment activity in this period.</p>}</section><section className="rounded-lg bg-white p-5 shadow-sm"><h2 className="font-semibold">Status overview</h2><div className="mt-4 space-y-2 text-sm"><p>Tasks: {analytics.tasks.completed || 0} completed, {analytics.tasks.pending || 0} pending, {analytics.tasks.overdue || 0} overdue</p><p>Leave: {analytics.leaves.pending || 0} pending, {analytics.leaves.approved || 0} approved, {analytics.leaves.rejected || 0} rejected</p><p>Projects: {analytics.projects.active || 0} active, {analytics.projects.completed || 0} completed</p><p>Meetings: {analytics.meetings.today || 0} today, {analytics.meetings.week || 0} this week, {analytics.meetings.month || 0} this month</p></div></section></div></DashboardLayout>;
}
export default Reports;
